export interface NavItem {
  title: string;
  slug: string;
}
export interface NavSection {
  title: string;
  dir: string;
  items: NavItem[];
}
export const NAV_SECTIONS: NavSection[] = [
  {
    title: 'Get Started',
    dir: 'get-started',
    items: [
      { title: 'Quick Start', slug: 'get-started/five-minute-start' },
      { title: 'Installation', slug: 'get-started/installation' },
      { title: 'Your First Session', slug: 'get-started/first-session' },
    ],
  },
  {
    title: 'Concepts',
    dir: 'concepts',
    items: [
      { title: 'Architecture', slug: 'concepts/architecture' },
      { title: 'Your Team', slug: 'concepts/your-team' },
      { title: 'Memory & Knowledge', slug: 'concepts/memory-and-knowledge' },
      { title: 'Parallel Work', slug: 'concepts/parallel-work' },
      { title: 'GitHub Workflow', slug: 'concepts/github-workflow' },
      { title: 'Portability', slug: 'concepts/portability' },
    ],
  },
  {
    title: 'Core Features',
    dir: 'features',
    items: [
      { title: 'Team Setup', slug: 'features/team-setup' },
      { title: 'Work Routing', slug: 'features/routing' },
      { title: 'Model Selection', slug: 'features/model-selection' },
      { title: 'Response Modes', slug: 'features/response-modes' },
      { title: 'Parallel Execution', slug: 'features/parallel-execution' },
      { title: 'Memory', slug: 'features/memory' },
      { title: 'Skills', slug: 'features/skills' },
      { title: 'Directives', slug: 'features/directives' },
      { title: 'GitHub Issues', slug: 'features/github-issues' },
      { title: 'GitLab Issues', slug: 'features/gitlab-issues' },
      { title: 'Ralph — Work Monitor', slug: 'features/ralph' },
      { title: '@copilot Coding Agent', slug: 'features/copilot-coding-agent' },
      { title: 'Standalone Install (no npm)', slug: 'features/standalone-install' },
      { title: 'VS Code', slug: 'features/vscode' },
    ],
  },
  {
    title: 'Advanced Features',
    dir: 'features',
    items: [
      { title: 'Ceremonies', slug: 'features/ceremonies' },
      { title: 'Reviewer Protocol', slug: 'features/reviewer-protocol' },
      { title: 'Human Team Members', slug: 'features/human-team-members' },
      { title: 'Consult Mode', slug: 'features/consult-mode' },
      { title: 'Labels & Triage', slug: 'features/labels' },
      { title: 'PRD Mode', slug: 'features/prd-mode' },
      { title: 'Project Boards', slug: 'features/project-boards' },
      { title: 'Export & Import', slug: 'features/export-import' },
      { title: 'Upstream Inheritance', slug: 'features/upstream-inheritance' },
      { title: 'Marketplace', slug: 'features/marketplace' },
      { title: 'Plugins', slug: 'features/plugins' },
      { title: 'MCP', slug: 'features/mcp' },
      { title: 'Notifications', slug: 'features/notifications' },
      { title: 'Streams', slug: 'features/streams' },
      { title: 'Git Worktrees', slug: 'features/worktrees' },
      { title: 'Squad RC', slug: 'features/squad-rc' },
    ],
  },
  {
    title: 'Infrastructure',
    dir: 'features',
    items: [
      { title: 'Enterprise Platforms', slug: 'features/enterprise-platforms' },
      { title: 'Storage Provider', slug: 'features/storage-provider' },
      { title: 'Distributed Mesh', slug: 'features/distributed-mesh' },
      { title: 'Capability Routing', slug: 'features/capability-routing' },
      { title: 'Rate Limiting', slug: 'features/rate-limiting' },
      { title: 'KEDA Autoscaling', slug: 'features/keda-scaling' },
      { title: 'State Backends', slug: 'features/state-backends' },
      { title: 'Dual-Mode Deployment', slug: 'features/dual-mode-deployment' },
    ],
  },
  {
    title: 'Guides',
    dir: 'guide',
    items: [
      { title: 'GitHub Agentic Workflows', slug: 'guide/gh-aw' },
      { title: 'Choose Your Interface', slug: 'get-started/choose-your-interface' },
      { title: 'Your Personal Squad', slug: 'guide/personal-squad' },
      { title: 'Interactive Shell Guide', slug: 'guide/shell' },
      { title: 'Tips & Tricks', slug: 'guide/tips-and-tricks' },
      { title: 'Sample Prompts', slug: 'guide/sample-prompts' },
      { title: 'Recipes', slug: 'cookbook/recipes' },
      { title: 'Agent Framework Integration', slug: 'guide/agent-framework-integration' },
      { title: 'Building Extensions', slug: 'guide/building-extensions' },
      { title: 'Building Resilient Agents', slug: 'guide/building-resilient-agents' },
      { title: 'Extensibility', slug: 'guide/extensibility' },
      { title: 'GitHub Auth Setup', slug: 'guide/github-auth-setup' },
      { title: 'Contributing', slug: 'guide/contributing' },
      { title: 'Contributors', slug: 'guide/contributors' },
    ],
  },
  {
    title: 'Security',
    dir: 'features',
    items: [
      { title: 'Security Hardening', slug: 'features/security-hardening' },
    ],
  },
  {
    title: 'Scenarios',
    dir: 'scenarios',
    items: [
      { title: 'Existing Repo', slug: 'scenarios/existing-repo' },
      { title: 'New Project', slug: 'scenarios/new-project' },
      { title: 'Solo Developer', slug: 'scenarios/solo-dev' },
      { title: 'Mid-Project', slug: 'scenarios/mid-project' },
      { title: 'Issue-Driven Dev', slug: 'scenarios/issue-driven-dev' },
      { title: 'Team of Humans', slug: 'scenarios/team-of-humans' },
      { title: 'Multiple Squads', slug: 'scenarios/multiple-squads' },
      { title: 'Monorepo', slug: 'scenarios/monorepo' },
      { title: 'Large Codebase', slug: 'scenarios/large-codebase' },
      { title: 'Scaling Workstreams', slug: 'scenarios/scaling-workstreams' },
      { title: 'Open Source', slug: 'scenarios/open-source' },
      { title: 'CI/CD Integration', slug: 'scenarios/ci-cd-integration' },
      { title: 'Release Process', slug: 'scenarios/release-process' },
      { title: 'Upgrading', slug: 'scenarios/upgrading' },
      { title: 'Migration Guide', slug: 'get-started/migration' },
      { title: 'Private Repos', slug: 'scenarios/private-repos' },
      { title: 'Cross-Org Auth', slug: 'scenarios/cross-org-auth' },
      { title: 'Team Portability', slug: 'scenarios/team-portability' },
      { title: 'Team State Storage', slug: 'scenarios/team-state-storage' },
      { title: 'Multi-Codespace', slug: 'scenarios/multi-codespace' },
      { title: 'Switching Models', slug: 'scenarios/switching-models' },
      { title: 'Remote Q&A', slug: 'scenarios/remote-qa' },
      { title: 'Disaster Recovery', slug: 'scenarios/disaster-recovery' },
      { title: 'Client Compatibility', slug: 'scenarios/client-compatibility' },
      { title: 'Aspire Dashboard', slug: 'scenarios/aspire-dashboard' },
      { title: 'Keep My Squad', slug: 'scenarios/keep-my-squad' },
      { title: 'Troubleshooting', slug: 'scenarios/troubleshooting' },
      { title: 'Azure Container Apps', slug: 'scenarios/azure-container-apps' },
      { title: 'AKS Deployment', slug: 'scenarios/aks-deployment' },
      { title: 'Production Observability', slug: 'scenarios/production-observability' },
      { title: 'Production Troubleshooting', slug: 'scenarios/production-troubleshooting' },
    ],
  },
  {
    title: 'Reference',
    dir: 'reference',
    items: [
      { title: 'CLI', slug: 'reference/cli' },
      { title: 'SDK', slug: 'reference/sdk' },
      { title: 'SDK API Reference', slug: 'reference/api-reference' },
      { title: 'SDK Integration', slug: 'reference/integration' },
      { title: 'Tools & Hooks', slug: 'reference/tools-and-hooks' },
      { title: 'Config', slug: 'reference/config' },
      { title: 'Container Image', slug: 'reference/container-image' },
      { title: 'State Backend Selection', slug: 'reference/state-backend-selection' },
      { title: 'Glossary', slug: 'reference/glossary' },
    ],
  },
];
export const STANDALONE_PAGES = [
  { title: "What's New", slug: 'whatsnew' },
  { title: 'SDK-First Mode', slug: 'sdk-first-mode' },
  { title: 'Community', slug: 'community' },
  { title: 'Insider Program', slug: 'insider-program' },
];
