/**
 * Plugin runtime execution layer with capability-gated provider operations.
 * Implements governed lifecycle hooks and artifact generation without ambient arbitrary execution.
 */

import { join, normalize, isAbsolute } from 'node:path';
import type { StorageProvider } from '../storage/index.js';
import { appendAuditEvent, type PluginAuditState } from './plugin-state.js';
import type { LifecycleEventName, PluginRuntimeCapability } from './plugin-manifest.js';

export const LIFECYCLE_EVENT_NAMES = [
  'onInstall',
  'onEnable',
  'onDisable',
  'onBeforeSpawn',
  'onAfterTask',
  'onMemoryRefresh',
] as const satisfies readonly LifecycleEventName[];

export function isLifecycleEventName(value: string): value is LifecycleEventName {
  return (LIFECYCLE_EVENT_NAMES as readonly string[]).includes(value);
}

/**
 * Result of a provider operation execution.
 */
export interface ProviderOperationResult {
  success: boolean;
  message: string;
  artifactsGenerated: string[];
  error?: string;
}

/**
 * Context provided to provider operations.
 */
export interface ProviderOperationContext {
  pluginId: string;
  version: string;
  squadDir: string;
  storage: StorageProvider;
  lifecycle: LifecycleEventName;
}

/**
 * Registry of approved provider operations.
 * Each provider implements bounded, deterministic artifact generation.
 */
const APPROVED_PROVIDERS: Record<string, (ctx: ProviderOperationContext, outputPaths: string[]) => Promise<ProviderOperationResult>> = {
  /**
   * Graphify knowledge graph artifact generator.
   * Generates graph.json and GRAPH_REPORT.md from static repo/docs inputs.
   * Does NOT install graphifyy CLI or start MCP servers.
   */
  graphify: async (ctx: ProviderOperationContext, outputPaths: string[]): Promise<ProviderOperationResult> => {
    const artifactsGenerated: string[] = [];
    
    try {
      // Validate output paths
      for (const outputPath of outputPaths) {
        if (!isSafeOutputPath(outputPath)) {
          return {
            success: false,
            message: `Rejected unsafe output path: ${outputPath}`,
            artifactsGenerated: [],
            error: `Output path traversal detected: ${outputPath}`,
          };
        }
      }
      
      // Find the graph.json and report paths from outputPaths
      const graphJsonPath = outputPaths.find(p => p.endsWith('graph.json'));
      const reportPath = outputPaths.find(p => p.endsWith('.md'));
      
      if (!graphJsonPath) {
        return {
          success: false,
          message: 'No graph.json output path found in capability grant',
          artifactsGenerated: [],
          error: 'Missing required output path: */graph.json',
        };
      }
      
      // Generate graph.json (simplified static example)
      const graphData = {
        generated_at: new Date().toISOString(),
        plugin_id: ctx.pluginId,
        version: ctx.version,
        lifecycle: ctx.lifecycle,
        nodes: [
          { id: 'plugin-manifest', type: 'config', label: 'Plugin Manifest' },
          { id: 'runtime-capabilities', type: 'feature', label: 'Runtime Capabilities' },
          { id: 'lifecycle-hooks', type: 'feature', label: 'Lifecycle Hooks' },
        ],
        edges: [
          { source: 'plugin-manifest', target: 'runtime-capabilities', type: 'declares' },
          { source: 'runtime-capabilities', target: 'lifecycle-hooks', type: 'enables' },
        ],
        metadata: {
          provider: 'graphify',
          mode: 'static-deterministic',
          note: 'Generated from manifest and static repo metadata without external CLI execution',
        },
      };
      
      await ctx.storage.write(
        join(ctx.squadDir, graphJsonPath),
        JSON.stringify(graphData, null, 2) + '\n',
      );
      artifactsGenerated.push(graphJsonPath);
      
      // Generate GRAPH_REPORT.md if path is specified
      if (reportPath) {
        const report = [
          '# Graphify Knowledge Graph Report',
          '',
          `Generated: ${new Date().toISOString()}`,
          `Plugin: ${ctx.pluginId}@${ctx.version}`,
          `Lifecycle: ${ctx.lifecycle}`,
          '',
          '## Graph Summary',
          '',
          `- Nodes: ${graphData.nodes.length}`,
          `- Edges: ${graphData.edges.length}`,
          '',
          '## Nodes',
          '',
          ...graphData.nodes.map(node => `- **${node.id}** (${node.type}): ${node.label}`),
          '',
          '## Edges',
          '',
          ...graphData.edges.map(edge => `- ${edge.source} → ${edge.target} (${edge.type})`),
          '',
          '## Implementation Notes',
          '',
          'This graph was generated by the governed plugin runtime provider.',
          'The graphify provider operates deterministically from static inputs.',
          'No external CLI tools were installed or executed.',
          '',
        ].join('\n');
        
        await ctx.storage.write(join(ctx.squadDir, reportPath), report);
        artifactsGenerated.push(reportPath);
      }
      
      return {
        success: true,
        message: `Generated ${artifactsGenerated.length} Graphify artifacts`,
        artifactsGenerated,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        message: `Graphify provider failed: ${message}`,
        artifactsGenerated,
        error: message,
      };
    }
  },
};

/**
 * Execute a lifecycle hook with capability-gated provider operations.
 */
export async function executeLifecycleHook(
  pluginId: string,
  version: string,
  lifecycle: LifecycleEventName,
  capabilities: PluginRuntimeCapability[],
  storage: StorageProvider,
  squadDir: string,
  audit: PluginAuditState,
): Promise<ProviderOperationResult[]> {
  const results: ProviderOperationResult[] = [];
  const now = new Date().toISOString();
  
  // Find capabilities that apply to this lifecycle event
  const applicableCapabilities = capabilities.filter(cap =>
    cap.lifecycle.includes(lifecycle)
  );
  
  if (applicableCapabilities.length === 0) {
    appendAuditEvent(audit, {
      type: 'execution_blocked',
      plugin_id: pluginId,
      version,
      timestamp: now,
      message: `Lifecycle ${lifecycle}: no applicable capabilities`,
    });
    return results;
  }
  
  // Execute each applicable capability's provider operation
  for (const capability of applicableCapabilities) {
    const provider = APPROVED_PROVIDERS[capability.provider];
    
    if (!provider) {
      const errorResult: ProviderOperationResult = {
        success: false,
        message: `Unsupported provider: ${capability.provider}`,
        artifactsGenerated: [],
        error: `Provider "${capability.provider}" is not in approved provider registry`,
      };
      results.push(errorResult);
      
      appendAuditEvent(audit, {
        type: 'execution_blocked',
        plugin_id: pluginId,
        version,
        timestamp: now,
        message: `Lifecycle ${lifecycle}: provider "${capability.provider}" rejected (not approved)`,
      });
      continue;
    }
    
    // Validate capability type
    if (capability.type !== 'artifact-generation') {
      const errorResult: ProviderOperationResult = {
        success: false,
        message: `Unsupported capability type: ${capability.type}`,
        artifactsGenerated: [],
        error: `Only "artifact-generation" capability type is currently supported`,
      };
      results.push(errorResult);
      
      appendAuditEvent(audit, {
        type: 'execution_blocked',
        plugin_id: pluginId,
        version,
        timestamp: now,
        message: `Lifecycle ${lifecycle}: capability type "${capability.type}" rejected`,
      });
      continue;
    }
    
    // Execute the provider operation
    const ctx: ProviderOperationContext = {
      pluginId,
      version,
      squadDir,
      storage,
      lifecycle,
    };
    
    const result = await provider(ctx, capability.outputPaths);
    results.push(result);
    
    appendAuditEvent(audit, {
      type: result.success ? 'provider_invoked' : 'provider_error',
      plugin_id: pluginId,
      version,
      timestamp: now,
      message: `Lifecycle ${lifecycle}: provider "${capability.provider}" ${result.success ? 'succeeded' : 'failed'} - ${result.message}`,
    });
  }
  
  return results;
}

/**
 * Validate that an output path is safe (no traversal, no absolute paths).
 */
function isSafeOutputPath(outputPath: string): boolean {
  const normalized = normalize(outputPath).replaceAll('\\', '/');
  return !isAbsolute(outputPath)
    && normalized !== '..'
    && !normalized.startsWith('../')
    && !normalized.split('/').includes('..');
}

/**
 * Get approved provider names for validation.
 */
export function getApprovedProviderNames(): string[] {
  return Object.keys(APPROVED_PROVIDERS);
}
